### ISSUE TITLE
[5.01] Search::Elasticsearch::TestServer uses deprecated -D command line option

### ISSUE THREAD

**Issue by abraxxa** [elastic/elasticsearch-perl#111]
Message::Passing::Output::Search::Elasticsearch's t/named_index_and_type.t tests fail with:

```
Starting node: http://127.0.0.1:9600
starts elasticsearch
Option                Description                                              
------                -----------                                              
-E <KeyValuePair>     Configure a setting                                      
-V, --version         Prints elasticsearch version information and exits       
-d, --daemonize       Starts Elasticsearch in the background                   
-h, --help            show help                                                
-p, --pidfile <Path>  Creates a pid file in the specified path on start        
-q, --quiet           Turns off standard ouput/error streams logging in console
-s, --silent          show minimal output                                      
-v, --verbose         show verbose output                                      
ERROR: D is not a recognized option
```

Looks like https://metacpan.org/source/DRTECH/Search-Elasticsearch-5.01/lib/Search/Elasticsearch/TestServer.pm#L161.

**Comment by abraxxa** [comment]
Changing -Des to -E seems to be the correct new option but this results in this error message:

```
Starting node: http://127.0.0.1:9600
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
Likely root cause: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:100)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:249)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.Command.main(Command.java:62)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73)
Refer to the log for complete error details.
```

It seems path.conf has to be set, using $dir wasn't enough, /etc/elasticsearch requires root privileges and isn't portable.

**Comment by clintongormley** [comment]
Hi @abraxxa 

Thanks for reporting. I need to think about how to handle this - perhaps the TestServer classes should become part of the the 1_0/2_0/5_0 client packages instead.

**Comment by abraxxa** [comment]
I've released Message::Passing::Output::Search::Elasticsearch version 0.003 with 5.0 support although the (optional) test fails.

**Comment by abraxxa** [comment]
Hi @clintongormley ,
do you already have a plan how to handle this?

**Comment by clintongormley** [comment]
Hi @abraxxa 

I've been away at Elasticon - I'll start looking at this again shortly.

**Comment by abraxxa** [comment]
Thanks Clinton!

**Comment by abraxxa** [comment]
The 5.0 compatibility was fixed but it's still unusable, mainly because of missing docs to to use it.
I've looked at t/95_TestServer/00_test_server.t but which fails for me on Ubuntu using the official Elasticsearch packages because

- ES_HOME isn't set by them
- if set the test fails with:
> [ahartmai@ahartmai-nb:~/.cpanm/work/1491294063.5080/Search-Elasticsearch-5.02$ ]$ prove -vl t/95_TestServer/00_test_server.t 
> t/95_TestServer/00_test_server.t .. Missing required arguments: es_version at t/95_TestServer/00_test_server.t line 20.
> Dubious, test returned 255 (wstat 65280, 0xff00)
> No subtests run 
> 
> Test Summary Report
> -------------------
> t/95_TestServer/00_test_server.t (Wstat: 65280 Tests: 0 Failed: 0)
>   Non-zero exit status: 255
>   Parse errors: No plan found in TAP output
> Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.10 cusr  0.01 csys =  0.13 CPU)
> Result: FAIL
- when adding es_version => '5_0' it still fails with the error mentioned before about `java.nio.file.NoSuchFileException:  /usr/share/elasticsearch/config`
- adding `path.conf=$tempdir` overcomes this issue but leads to `ERROR: no log4j2.properties found; tried [/tmp/testserver-vROg0] and its subdirectories`

Wouldn't it best to include as tempdir and environment setup functionality into this module so a user doesn't has to care about that?
